# [2016-11-22] Auto-generated file, do not edit

PRODUCT_COPY_FILES += \
    vendor/huawei/angler/proprietary/bin/mm-qcamera-app:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qcamera-app:huawei \
    vendor/huawei/angler/proprietary/bin/nanoapp_cmd:$(TARGET_COPY_OUT_SYSTEM)/bin/nanoapp_cmd:huawei \
    vendor/huawei/angler/proprietary/bin/ssr_setup:$(TARGET_COPY_OUT_SYSTEM)/bin/ssr_setup:huawei \
    vendor/huawei/angler/proprietary/bin/subsystem_ramdump:$(TARGET_COPY_OUT_SYSTEM)/bin/subsystem_ramdump:huawei \
    vendor/huawei/angler/proprietary/etc/diag/Angler_Radio-general.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/diag/Angler_Radio-general.cfg:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/cneapiclient.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/cneapiclient.xml:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/com.android.omadm.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.omadm.service.xml:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/com.google.widevine.software.drm.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.google.widevine.software.drm.xml:huawei \
    vendor/huawei/angler/proprietary/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/activity_recognition.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/activity_recognition.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/audio.primary.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/audio.primary.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/context_hub.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/context_hub.default.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/gps.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/gps.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/nfc_nci.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/nfc_nci.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib64/hw/sensors.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/sensors.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libfilterpack_facedetect.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfilterpack_facedetect.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgps.utils.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libhubconnection.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhubconnection.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libimscamera_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimscamera_jni.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libimsmedia_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimsmedia_jni.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libManufacture.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libManufacture.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libprotobuf-cpp-full.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libprotobuf-cpp-full.so:huawei \
    vendor/huawei/angler/proprietary/lib64/libtinyxml.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libtinyxml.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/activity_recognition.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/activity_recognition.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/audio.primary.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.primary.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/camera.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/context_hub.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/context_hub.default.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/gps.msm8994.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.msm8994.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/nfc_nci.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/nfc_nci.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib/hw/sensors.angler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.angler.so:huawei \
    vendor/huawei/angler/proprietary/lib/libdmengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmengine.so:huawei \
    vendor/huawei/angler/proprietary/lib/libdmjavaplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmjavaplugin.so:huawei \
    vendor/huawei/angler/proprietary/lib/libfilterpack_facedetect.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfilterpack_facedetect.so:huawei \
    vendor/huawei/angler/proprietary/lib/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgps.utils.so:huawei \
    vendor/huawei/angler/proprietary/lib/libhubconnection.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhubconnection.so:huawei \
    vendor/huawei/angler/proprietary/lib/libimscamera_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimscamera_jni.so:huawei \
    vendor/huawei/angler/proprietary/lib/libimsmedia_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimsmedia_jni.so:huawei \
    vendor/huawei/angler/proprietary/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_interface.so:huawei \
    vendor/huawei/angler/proprietary/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmjpeg_interface.so:huawei \
    vendor/huawei/angler/proprietary/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmm-qcamera.so:huawei \
    vendor/huawei/angler/proprietary/lib/libqomx_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqomx_core.so:huawei \
    vendor/huawei/angler/proprietary/lib/libtinyxml.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libtinyxml.so:huawei \
    vendor/huawei/angler/proprietary/lib/soundfx/libfmas.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libfmas.so:huawei \
